/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KuisPBO;

/**
 *
 * @author mmillania
 */
public class MotorMain {
    public static void main(String[] args) {
        Motor h = new Motor("Beat", "TipeHonda");
        System.out.println(h.getMerk());
        System.out.println(h.getTipe());
        h.status();
        h.tambahKecepatan();
        System.out.println();
        h.kurangKecepatan();
        h.status();
        
        h.hidup();
        System.out.println("-----Menambah Kecepatan----");
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        h.tambahKecepatan();
        
        
        System.out.println("------Mengurangi kecepatan----");
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.kurangKecepatan();
        h.status();
        h.mati();
        System.out.println("=================================================================================");
    
        Motor y = new Motor("Mio", "TipeYamaha");
        System.out.println(y.getMerk());
        System.out.println(y.getTipe());
        y.status();
        y.tambahKecepatan();
        System.out.println();
        y.kurangKecepatan();
        y.status();
        
        y.hidup();
        System.out.println("-----Menambah Kecepatan----");
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        y.tambahKecepatan();
        System.out.println("------Mengurangi kecepatan----");
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.kurangKecepatan();
        y.status();
        y.mati();
        System.out.println("=================================================================================");
        
        Motor s = new Motor("FU","TipeSuzuki");
        System.out.println(s.getMerk());
        System.out.println(s.getTipe());
        s.status();
        s.tambahKecepatan();
        System.out.println();
        s.kurangKecepatan();
        s.status();
        
        s.hidup();
        System.out.println("-----Menambah Kecepatan----");
        s.tambahKecepatan();
        s.tambahKecepatan();
        s.tambahKecepatan();
        s.tambahKecepatan();
        s.tambahKecepatan();
        s.tambahKecepatan();
        s.tambahKecepatan();
        s.tambahKecepatan();
        s.tambahKecepatan();
        
        
        System.out.println("------Mengurangi kecepatan----");
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
        s.kurangKecepatan();
       
        s.status();
        s.mati();
        System.out.println("=================================================================================");
        Motor d = new Motor("Ninja", "TipeDucati");
        System.out.println(d.getMerk());
        System.out.println(d.getTipe());
        d.status();
        d.tambahKecepatan();
        System.out.println();
        d.kurangKecepatan();
        d.status();
        
        d.hidup();
        System.out.println("-----Menambah Kecepatan----");
        d.tambahKecepatan();
        d.tambahKecepatan();
        d.tambahKecepatan();
        d.tambahKecepatan();
        d.tambahKecepatan();
        d.tambahKecepatan();
        d.tambahKecepatan();
        d.tambahKecepatan();
        
        
        System.out.println("------Mengurangi kecepatan----");
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.kurangKecepatan();
        d.status();
        d.mati();
        System.out.println("=================================================================================");
}
    
}
